-- revenue_retention.sql
-- Purpose:
-- Measure how revenue from each customer cohort changes over time.
-- Output:
-- One row per cohort_month and cohort_age showing
-- revenue, base revenue, and revenue retention percentage.

WITH orders_clean AS (

    -- Use customer_unique_id instead of customer_id
    -- to track actual customers across multiple orders.
    SELECT
        c.customer_unique_id,
        DATE_TRUNC('month', o.order_date) AS order_month,
        o.revenue

    FROM orders o
    JOIN customers c
        ON o.customer_id = c.customer_id

),

first_purchase AS (

    -- Determine each customer's first purchase month.
    SELECT
        customer_unique_id,
        MIN(order_month) AS cohort_month

    FROM orders_clean

    GROUP BY customer_unique_id

),

cohort_base AS (

    -- Attach the cohort month to every order
    -- and calculate months since first purchase.
    SELECT
        o.customer_unique_id,
        o.order_month,
        f.cohort_month,

        DATE_DIFF(
            o.order_month,
            f.cohort_month,
            MONTH
        ) AS cohort_age,

        o.revenue

    FROM orders_clean o
    JOIN first_purchase f
        ON o.customer_unique_id = f.customer_unique_id

),

cohort_revenue AS (

    -- Calculate total revenue generated by each cohort
    -- at every stage of its lifecycle.
    SELECT
        cohort_month,
        cohort_age,
        SUM(revenue) AS revenue

    FROM cohort_base

    GROUP BY
        cohort_month,
        cohort_age

),

cohort_base_revenue AS (

    -- Month 0 revenue becomes the baseline
    -- for calculating revenue retention.
    SELECT
        cohort_month,
        revenue AS base_revenue

    FROM cohort_revenue

    WHERE cohort_age = 0

)

-- Revenue Retention % = Current Revenue / Base Revenue

SELECT

    r.cohort_month,
    r.cohort_age,
    r.revenue,
    b.base_revenue,

    ROUND(
        100.0 * r.revenue / NULLIF(b.base_revenue, 0),
        2
    ) AS revenue_retention_pct

FROM cohort_revenue r

JOIN cohort_base_revenue b
    ON r.cohort_month = b.cohort_month

ORDER BY
    r.cohort_month,
    r.cohort_age;
